- cmd/gomarkdoc/command.go
- lang/package.go
Fixes the outputted import path when using local paths on Windows and using `/` as a path separator instead of the native `\`
> support unix paths on windows

- .github/workflows/release.yml
- .goreleaser.yml
Adds a configuration for goreleaser and a GitHub Action for running a release on each new tag pushed to the repository.
> ci: add artifact bundling via goreleaser

- .github/workflows/test.yml
- lang/README.md
- lang/config.go
The existing code calls `remote.List()` to get the list of branches per remote. However, this call actually fetches the branches from the remote. Doing so both slows the call down and requires authentication, which requires extra configuration and is not always set up.
This change switches to listing references on the repository itself, which requires no fetch from the remote and therefore no authentication, while still being able to find the refs on the remote and determine the default branch.
> fix(lang): use local refs for repo resolution to bypass authentication

- format/devops.go
- format/devops_test.go
On windows, Azure DevOps code links encode the path segment of the href with backslashes. This change correctly encodes them with unix-style forward slashes.
> fix(format): properly encode path in code href on windows

- .github/workflows/test.yml
- lang/README.md
The continuous integration setup doesn't have a ref for the default branch on the origin remote. This breaks code link generation in ci, which causes the doc verification to fail. This change adds a step to populate the default branch in the ci steup.
> ci: set default branch to fix link detection

- .github/workflows/release.yml
The latest version of goreleaser uses golang 1.14 and has target architectures not supported in golang 1.13.
> ci: upgrade release workflow to go 1.14

- .github/workflows/test.yml
The existing mage action appears to be malfunctioning in recent builds. This switches to the official mage action that is now available.
> ci: switch to official mage action

- lang/README.md
- lang/example.go
- templates.go
- templates/example.gotxt
Closes #26 
This MR includes example output along with the code that generates that output. Given `foo.go`:
```go
package foo
import "fmt"
func Hello(name string) string {
return fmt.Sprintf("Hello %s!", name)
}
```
and `foo_test.go`:
```go
package foo
import "fmt"
func ExampleHello() {
fmt.Println(Hello("foo"))
// Output: Hello foo!
}
```
the output looks like this:
````markdown
<details><summary>Example</summary>
<p>
```go
{
fmt.Println(Hello("foo"))
}
```
Outputs:
```output
Hello foo!
```
</p>
</details>
````
Note, this MR also includes a `go mod tidy`. This might overlap with #25, so this can be altered if necessary. Additionally, I ended up using the markdown code fence type `output` as a descriptor, but I don't know if there's a better descriptor to use here.
> feat(lang): show expected output for examples

- README.md
- cmd/gomarkdoc/README.md
- cmd/gomarkdoc/doc.go
- doc.go
- format/README.md
- format/base.go
- format/base_test.go
- go.mod
- go.sum
Links should be preserved as they are and allowed to be turned into clickable links by variants such as GFM. This change omits any detected URLs from escaping while continuing to escape anything that's not detected as a URL.
While adding tests I discovered strikethroughs weren't being escaped properly, so that's fixed in here too.
fixes #29
> fix(format): bypass escaping of links, add strikethrough escape

- README.md
- doc.go
The move to the go modules version of blackfriday means that `go get` must run in module mode to install the tool. Setting `GO111MODULE=on` when running the command ensures this for recent versions of golang.
fixes #31
> docs(readme): add GO111MODULE=on to installation command

- README.md
- doc.go
The README.md contains `--repository.defaultBranch` which should be `--repository.default-branch`
Thanks for the great project @princjef!
> docs(readme): fix arg format in repository example

- cmd/gomarkdoc/command.go
This change is related to the issue https://github.com/princjef/gomarkdoc/issues/35. It creates all the required folders when specifying the output parameter.
> feat(cmd): automatically create parent folders for output file

- cmd/gomarkdoc/README.md
- cmd/gomarkdoc/command.go
- cmd/gomarkdoc/command_test.go
The existing check logic is custom, complicated and isn't working correctly right now. Simplifying to a hash comparison fixes the issue and makes the code much more maintainable.
> fix(cmd): perform equality check using hashes

- lang/func.go
Example names for functions don't properly compute the name of the example if it has a special name because it's being extracted from the prefix, not the full name. This fixes that mistake.
Fixes #47
> fix(lang): compute func example name correctly

- README.md
- doc.go
Adds installation instructions with `go install` for golang 1.16+
Fixes #49
> docs(readme): update installation instructions

- README.md
- cmd/gomarkdoc/README.md
- cmd/gomarkdoc/command.go
- doc.go
Adds a new `--tags` option for specifying build tags when picking files to include for documentation generation. Also supports use of `GOFLAGS` for specifying build tags (overridden by use of `--tags` or `tags` in the config file).
Fixes #48
> feat(cmd): add support for build tags

- lang/README.md
- lang/func.go
Functions are rendered today using the same formatting as the original source code, including multiline rendering of the signature where used. This is inconsistent with godoc representation and is problematic for rendering as a link in the package index.
This change converts the rendering of the function signature to "standard" rendering, which renders function arguments on a single line by default.
Fixes #46
> fix(lang): render function signatures using standard formatting

- .github/workflows/release.yml
- .github/workflows/test.yml
- magefile.go
Updates the precompiled binary to golang 1.17 and updates the version of golangci-lint to its latest (1.43.0)
> ci: update to golang build verion to 1.17 and update linter

- .github/workflows/release.yml
- .github/workflows/test.yml
- .golangci.yml
- go.mod
- go.sum
- magefile.go
The latest binaries don't work on go 1.18. This updates the test and release workflows to use the new language version
> ci: switch to go 1.18 for test and release

- cmd/gomarkdoc/output.go
The check will fail when using `gomarkdoc -c -e ...`. This unfortunately breaks support for running gomarkdown in CI (or other hooks).
The issue is that the embedding is not run when `-c` is set. This changes ensures that the embedding takes place as long as `-o ...` is given.
> fix(cmd): support embed when running in check mode

- go.mod
- go.sum
- lang/func.go
- lang/func_test.go
- testData/lang/function/func.go
- testData/lang/function/func_test.go
This PR also updates golang version to 1.18 to make tests works.
> fix(lang): compute correct name for parameterized method receivers

- README.md
- doc.go
Adds section describing how this tool uses itself to generate its READMEs and creates a place for additional projects to be listed.
Fixes #61
> docs(readme): add section with usage examples

- cmd/gomarkdoc/command_test.go
- cmd/gomarkdoc/output.go
- magefile.go
Fixed incorrect folder permission introduced by the #72. Also added `build` target in mage for development purposes
> fix(cmd): correct permissions of created files and folders

- magefile.go
The current coverage measurement only tracks intra-package coverage, which is very impractical for something that is best verified through snapshot testing. This changes that pattern to encourage more full system tests
> ci: improve coverage measurement
